### ISSUE TITLE
Use the term "property based testing" somewhere

### ISSUE THREAD

**Issue by nightscape** [justincampbell/generative#23]
Hi Justin,

even though I had searched extensively, I had completely missed generative because I was looking for "property based testing".
It might be worth adding that term to the project description and or README so that Google and Github will let people find this lovely gem :)

**Comment by nightscape** [comment]
This is a link to check if generative can be found on Github:
https://github.com/search?l=Ruby&o=desc&q=property+testing&ref=opensearch&s=updated&type=Repositories

**Comment by justincampbell** [comment]
Added to repo desc

**Comment by nightscape** [comment]
Nice! :D
