### ISSUE TITLE
Please make a new Gem release

### ISSUE THREAD

**Issue by xxx** [justincampbell/generative#38]
I ran into https://github.com/justincampbell/generative/issues/37 when using the published gem, but the problem has already been resolved in `master`, years ago.

Please release a new version of the gem

**Comment by olleolleolle** [comment]
The CHANGELOG needs elements from this list of commits: 

https://github.com/justincampbell/generative/compare/v0.2.4...master

**Comment by olleolleolle** [comment]
I can also see that the existing CHANGELOG document needs dates and version number headings (preferably with a link to the "compare" link on GitHub for each version.

**Comment by olleolleolle** [comment]
@justincampbell @xxx I think  we are now ready for me to try releasing the patch version.

**Comment by olleolleolle** [comment]
We have liftoff. v0.2.5 is out.

![bild](https://user-images.githubusercontent.com/211/151024580-7b5a2145-e120-4872-9f81-35572d8e2235.png)
